on: push
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.SUK_HOST}}
        username: ${{secrets.SUK_USERNAME}}
        password: ${{secrets.SUK_PASSWORD}}
